# NumPy

In [23]:
import numpy as np

In [24]:
np.sqrt(16)

np.float64(4.0)

In [25]:
np.log(4)

np.float64(1.3862943611198906)

In [26]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [27]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [28]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [29]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [30]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [31]:
np.array([2, 3, 4])*100

array([200, 300, 400])

In [32]:
np.array([2, 3, 4]) + np.array([7, 12, 8])

array([ 9, 15, 12])

In [33]:
(np.array([2, 3, 4]) + np.array([7, 12, 8])) / 2

array([4.5, 7.5, 6. ])

In [35]:
m = np.array([[2, 5], 
              [6, 8],
              [1, 3]])

In [36]:
# Количество измерений
m.ndim

2

In [37]:
# Форма массива
m.shape

(3, 2)

In [38]:
# Размер массива
m.size

6

In [39]:
m[1][0]

np.int64(6)

In [42]:
m[1,0]

np.int64(6)

In [43]:
m[1]

array([6, 8])

In [45]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [46]:
m[1:]

array([[6, 8],
       [1, 3]])