# NumPy

In [181]:
import numpy as np

In [182]:
np.sqrt(16)

np.float64(4.0)

In [183]:
np.log(4)

np.float64(1.3862943611198906)

In [184]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [185]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [186]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [187]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [188]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [189]:
np.array([2, 3, 4])*100

array([200, 300, 400])

In [190]:
np.array([2, 3, 4]) + np.array([7, 12, 8])

array([ 9, 15, 12])

In [191]:
(np.array([2, 3, 4]) + np.array([7, 12, 8])) / 2

array([4.5, 7.5, 6. ])

In [192]:
m = np.array([[2, 5], 
              [6, 8],
              [1, 3]])

In [193]:
# Количество измерений
m.ndim

2

In [194]:
# Форма массива
m.shape

(3, 2)

In [195]:
# Размер массива
m.size

6

In [196]:
m[1][0]

np.int64(6)

In [197]:
m[1,0]

np.int64(6)

In [198]:
m[1]

array([6, 8])

In [199]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [200]:
m[1:]

array([[6, 8],
       [1, 3]])

In [201]:
m[::2]

array([[2, 5],
       [1, 3]])

In [202]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

In [203]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4])

In [204]:
marks.min()

np.int64(3)

In [205]:
marks.max()

np.int64(5)

In [206]:
# Выдает индекс элемента с наибольшим значением
marks.argmax()

np.int64(0)

In [207]:
# Выдает индекс элемента с наименьшим значением
marks.argmin()

np.int64(2)

In [208]:
m

array([[2, 5],
       [6, 8],
       [1, 3]])

In [209]:
m.mean(axis = 1)

array([3.5, 7. , 2. ])

In [210]:
m.max(axis = 1)

array([5, 8, 3])

In [211]:
# По стобцам
m.min(axis = 0)

array([1, 3])

In [212]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [214]:
# Генерирует рандомные числа в заданном диапазоне
np.linspace(50, 80, 20)

array([50.        , 51.57894737, 53.15789474, 54.73684211, 56.31578947,
       57.89473684, 59.47368421, 61.05263158, 62.63157895, 64.21052632,
       65.78947368, 67.36842105, 68.94736842, 70.52631579, 72.10526316,
       73.68421053, 75.26315789, 76.84210526, 78.42105263, 80.        ])

In [215]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [216]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [217]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [218]:
ages = np.array(([15, 23, 32, 45, 52],
                 [58, 34, 55, 78, 20],
                 [25, 67, 33, 45, 14]))

ages

array([[15, 23, 32, 45, 52],
       [58, 34, 55, 78, 20],
       [25, 67, 33, 45, 14]])

In [219]:
ages > 20

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False]])

In [220]:
new_arr = (ages > 17) & (ages < 60)
new_arr

array([[False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True,  True, False]])

In [221]:
new_arr.sum()

np.int64(11)

In [224]:
new_arr = ages[(ages > 17) & (ages < 57)]
new_arr

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])

In [225]:
new_arr.reshape(5, 2)
new_arr.flatten()

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])

In [226]:
new_arr.transpose()

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])

In [227]:
new_arr.T

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])

In [233]:
m[0][0] = 10 

In [234]:
m

array([[10,  5],
       [ 6,  8],
       [ 1,  3]])

In [236]:
income = np.array([[20_000, 30_000, 25_000, 700_000],
                   [23_000, 35_000, 20_000, 32_000]])

In [237]:
np.log(income)

array([[ 9.90348755, 10.30895266, 10.1266311 , 13.45883561],
       [10.04324949, 10.46310334,  9.90348755, 10.37349118]])