# NumPy

In [127]:
import numpy as np

In [128]:
np.sqrt(16)

np.float64(4.0)

In [129]:
np.log(4)

np.float64(1.3862943611198906)

In [130]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [131]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [132]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [133]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [134]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [135]:
np.array([2, 3, 4])*100

array([200, 300, 400])

In [136]:
np.array([2, 3, 4]) + np.array([7, 12, 8])

array([ 9, 15, 12])

In [137]:
(np.array([2, 3, 4]) + np.array([7, 12, 8])) / 2

array([4.5, 7.5, 6. ])

In [138]:
m = np.array([[2, 5], 
              [6, 8],
              [1, 3]])

In [139]:
# Количество измерений
m.ndim

2

In [140]:
# Форма массива
m.shape

(3, 2)

In [141]:
# Размер массива
m.size

6

In [142]:
m[1][0]

np.int64(6)

In [143]:
m[1,0]

np.int64(6)

In [144]:
m[1]

array([6, 8])

In [145]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [146]:
m[1:]

array([[6, 8],
       [1, 3]])

In [147]:
m[::2]

array([[2, 5],
       [1, 3]])

In [148]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

In [149]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4])

In [150]:
marks.min()

np.int64(3)

In [151]:
marks.max()

np.int64(5)

In [152]:
# Выдает индекс элемента с наибольшим значением
marks.argmax()

np.int64(0)

In [153]:
# Выдает индекс элемента с наименьшим значением
marks.argmin()

np.int64(2)

In [154]:
m

array([[2, 5],
       [6, 8],
       [1, 3]])

In [155]:
m.mean(axis = 1)

array([3.5, 7. , 2. ])

In [156]:
m.max(axis = 1)

array([5, 8, 3])

In [157]:
# По стобцам
m.min(axis = 0)

array([1, 3])

In [158]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [160]:
# Генерирует рандомные числа в заданном диапазоне
np.linspace(50, 80, 20)

array([50.        , 51.57894737, 53.15789474, 54.73684211, 56.31578947,
       57.89473684, 59.47368421, 61.05263158, 62.63157895, 64.21052632,
       65.78947368, 67.36842105, 68.94736842, 70.52631579, 72.10526316,
       73.68421053, 75.26315789, 76.84210526, 78.42105263, 80.        ])

In [161]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [162]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [163]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [164]:
ages = np.array(([15, 23, 32, 45, 52],
                 [58, 34, 55, 78, 20],
                 [25, 67, 33, 45, 14]))

ages

array([[15, 23, 32, 45, 52],
       [58, 34, 55, 78, 20],
       [25, 67, 33, 45, 14]])

In [165]:
ages > 20

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False]])

In [166]:
new_arr = (ages > 17) & (ages < 60)
new_arr

array([[False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True,  True, False]])

In [167]:
new_arr.sum()

np.int64(11)

In [168]:
new_arr = ages[(ages > 17) & (ages < 60)]
new_arr

array([23, 32, 45, 52, 58, 34, 55, 20, 25, 33, 45])

In [177]:
new_arr.reshape(5, 2)
new_arr.flatten()

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [179]:
new_arr.transpose()

[23 32 45 52 58 34 55 20 25 33 45]


array([23, 32, 45, 52, 58, 34, 55, 20, 25, 33, 45])

In [180]:
new_arr.T

array([23, 32, 45, 52, 58, 34, 55, 20, 25, 33, 45])