# NumPy

In [51]:
import numpy as np

In [52]:
np.sqrt(16)

np.float64(4.0)

In [53]:
np.log(4)

np.float64(1.3862943611198906)

In [54]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [55]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [56]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [57]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [58]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [59]:
np.array([2, 3, 4])*100

array([200, 300, 400])

In [60]:
np.array([2, 3, 4]) + np.array([7, 12, 8])

array([ 9, 15, 12])

In [61]:
(np.array([2, 3, 4]) + np.array([7, 12, 8])) / 2

array([4.5, 7.5, 6. ])

In [62]:
m = np.array([[2, 5], 
              [6, 8],
              [1, 3]])

In [63]:
# Количество измерений
m.ndim

2

In [64]:
# Форма массива
m.shape

(3, 2)

In [65]:
# Размер массива
m.size

6

In [66]:
m[1][0]

np.int64(6)

In [67]:
m[1,0]

np.int64(6)

In [68]:
m[1]

array([6, 8])

In [69]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [70]:
m[1:]

array([[6, 8],
       [1, 3]])

In [71]:
m[::2]

array([[2, 5],
       [1, 3]])

In [72]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

In [73]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4])

In [74]:
marks.min()

np.int64(3)

In [75]:
marks.max()

np.int64(5)

In [78]:
# Выдает индекс элемента с наибольшим значением
marks.argmax()

np.int64(0)

In [80]:
# Выдает индекс элемента с наименьшим значением
marks.argmin()

np.int64(2)