# NumPy

In [7]:
import numpy as np

In [8]:
np.sqrt(16)

np.float64(4.0)

In [9]:
np.log(4)

np.float64(1.3862943611198906)

In [10]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [11]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [14]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [17]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [18]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [19]:
np.array([2, 3, 4])*100

array([200, 300, 400])