# NumPy

In [81]:
import numpy as np

In [82]:
np.sqrt(16)

np.float64(4.0)

In [83]:
np.log(4)

np.float64(1.3862943611198906)

In [84]:
np.mean([20, 40, 30, 450, 45, 30])

np.float64(102.5)

In [85]:
np.median([20, 40, 30, 450, 45, 30])

np.float64(35.0)

In [86]:
np.array([[2, 3, 4], [1, 2, 3.0]])

array([[2., 3., 4.],
       [1., 2., 3.]])

In [87]:
np.array([[2, 3, '4'], [1, 2, 3.0]])

array([['2', '3', '4'],
       ['1', '2', '3.0']], dtype='<U32')

In [88]:
np.array([2, 3, 4])**2

array([ 4,  9, 16])

In [89]:
np.array([2, 3, 4])*100

array([200, 300, 400])

In [90]:
np.array([2, 3, 4]) + np.array([7, 12, 8])

array([ 9, 15, 12])

In [91]:
(np.array([2, 3, 4]) + np.array([7, 12, 8])) / 2

array([4.5, 7.5, 6. ])

In [92]:
m = np.array([[2, 5], 
              [6, 8],
              [1, 3]])

In [93]:
# Количество измерений
m.ndim

2

In [94]:
# Форма массива
m.shape

(3, 2)

In [95]:
# Размер массива
m.size

6

In [96]:
m[1][0]

np.int64(6)

In [97]:
m[1,0]

np.int64(6)

In [98]:
m[1]

array([6, 8])

In [99]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [100]:
m[1:]

array([[6, 8],
       [1, 3]])

In [101]:
m[::2]

array([[2, 5],
       [1, 3]])

In [102]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

In [103]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4])

In [104]:
marks.min()

np.int64(3)

In [105]:
marks.max()

np.int64(5)

In [106]:
# Выдает индекс элемента с наибольшим значением
marks.argmax()

np.int64(0)

In [107]:
# Выдает индекс элемента с наименьшим значением
marks.argmin()

np.int64(2)

In [108]:
m

array([[2, 5],
       [6, 8],
       [1, 3]])

In [109]:
m.mean(axis = 1)

array([3.5, 7. , 2. ])

In [110]:
m.max(axis = 1)

array([5, 8, 3])

In [111]:
# По стобцам
m.min(axis = 0)

array([1, 3])